apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: customer
    version: v1
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
      version: v1
  template:
    metadata:
      labels:
        app: customer
        version: v1
    spec:
      containers:
      - name: preference
        env:
        - name: JAVA_OPTIONS
          value: '-Djavax.net.ssl.trustStore=/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword=changeme'
        image: quay.io/raffaelespazzoli/e2e-encryption-tutorial-customer:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
