apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: route-${route}
  namespace: ${namespace}
spec:
  secretName: route-${route}
  commonName: ${host}
  dnsNames:
  - ${host}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  acme:
    config:
    - dns01:
        provider: cluster-dns
      domains:
      - '${host}'
  keyEncoding: pkcs8       